### ISSUE TITLE
Increasing the interactive coding window size

### ISSUE THREAD

**Issue by kgashok** [ronreiter/interactive-tutorials#123]
The coding window size is too small for attempting say 40-45 lines of code. Is there a way we can pop out that section into  a new window and plug it back in?

**Comment by ronreiter** [comment]
If someone can implement a button that expands the window then I will merge the PR.

**Comment by quinnlas** [comment]
```css
footer#dock.maximized {
    height: 500px;
}

div.CodeMirror.cm-s-xq-light {
  height: 400px;
}
```
A simple workaround would be to paste this into a user CSS browser extension.
